### PR TITLE
Improve Mastercard 2Bin regex

### PR DESCRIPTION
**Pull request by seamuslee001**
As per https://github.com/thephpleague/omnipay-common/pull/111 Improve the regex for 2 Bin Mastercard testing.

### CODE REVIEW

**Comment by seamuslee001** [comment]
ping @Moosh-be

**Comment by Moosh-be** [comment]
tests still valid but are not updated to cover your specific improvement.
---
Do you want  to update tests ?

I can merge or wait.

**Comment by Moosh-be** [comment]
@gauthierm  why this package still "alpha" ?

**Comment by seamuslee001** [comment]
@Moosh-be I'll look to add a test for the 677189 Bin but i think given that this is passing the tests it suggesting that the regex i stumbled upon at least does not break anything currently

**Comment by kktsvetkov** [comment]
Will you do a new release with that MasterCard new numbers fix ?

**Pull request merged**
